runtime: python312  # Python 3.12 runtime
entrypoint: gunicorn -b :$PORT app:app  # Gunicorn web server with your Flask app

instance_class: F1  # Choose an instance class based on your needs

env_variables:
  DATA_PATH: "C:\\Code - Copy\\__PYPROJECTS\\JuniperWeb\\Static\\pstep.csv"  # Environment variable for data path

automatic_scaling:
  target_cpu_utilization: 0.65  # Scale based on CPU utilization
  min_instances: 1  # Minimum number of instances
  max_instances: 5  # Maximum number of instances

# You can add more configurations like resource limits, network settings, etc.
